[deps]
ActuaryUtilities = "bdd23359-8b1c-4f88-b89b-d11982a786f4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
FinanceModels = "77f2ae65-bdde-421f-ae9d-22f1af19dd76"
MortalityTables = "4780e19d-04b9-53dc-86c2-9e9aa59b5a12"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
